# Generated by Django 5.2.8 on 2025-12-05 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_tg_chat_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="tg_chat_id",
            new_name="telegram_chat_id",
        ),
    ]
