# Generated by Django 5.2.8 on 2025-12-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habitica", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="last_notified",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Последнее уведомление"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(verbose_name="Время выполнения"),
        ),
    ]
