# Generated by Django 5.2.8 on 2025-12-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habitica", "0003_habit_last_notified_alter_habit_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="last_completed",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Последнее выполнение"
            ),
        ),
    ]
