# Generated by Django 5.2.8 on 2025-12-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habitica", "0004_habit_last_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="last_notified",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Последнее уведомление"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.CharField(
                choices=[
                    ("", "не выбрано"),
                    ("day", "ежедневная"),
                    ("two_days", "каждые два дня"),
                    ("three_days", "каждые три дня"),
                    ("four_days", "каждые четыре дня"),
                    ("five_days", "каждые пять дней"),
                    ("six_days", "каждые шесть дней"),
                    ("week", "еженедельная"),
                ],
                default="day",
                max_length=255,
                verbose_name="Периодичность",
            ),
        ),
    ]
